### ISSUE TITLE
sandbox out of memory error

### ISSUE THREAD

**Issue by tyeth** [joaomoreno/gifcap#31]
Didn't capture screenshot of error, but in chrome (latest) got an AW SNAP, with SBOX_FATAL_MEMORY_EXCEEDED  so clearly just tried too large video. Was probably three or four minutes of a 1080p *tab* recording, selected to skip first 30seconds (while previewing) then chose render and crashed. (Also my chrome has a lot of tabs open, but mostly suspended using The Great Suspender so no random crashing tabs elsewhere). Given site full permissions and no adblock.

**Comment by joaomoreno** [comment]
Thanks for the lots of details!

Is this something you can repro?

**Comment by nikonso** [comment]
Hi, 

Jut hit this two times by recording one chrome tab
![image](https://user-images.githubusercontent.com/16099035/110006759-eda71c00-7d11-11eb-8f4c-a98f7d068f4a.png)

After 3 minutes of recording this happens
![image](https://user-images.githubusercontent.com/16099035/110006851-04e60980-7d12-11eb-8224-5978168aebea.png)

If you need more details feel free to ask

**Comment by joaomoreno** [comment]
If you're trying to record 3 minutes of an entire Chrome tab, you should probably not use GIFs.

**Comment by nikonso** [comment]
Yeah that makes total sense, in my defense when I started the recording it wasn't supposed to be that long :D 

One quick suggestion, that you can ignore if you feel it's not worth the trouble. Would it be possible to instead o hard crashing, to simply have a limit on how long we can record, so that the data up until that point isn't lost?
