### ISSUE TITLE
Shortcut, Chrome extension or floating button to start/stop recording

### ISSUE THREAD

**Issue by laura-gil** [joaomoreno/gifcap#54]
Hi João Moreno!

First I want to than you for this amazing GIF recorder. It has honestly improved my workflow 10000% to a point that I have recommended it to all my coworkers.

An area of improvement would be to be able somehow to start/stop the recording without having to go to the tab that has the recorder.

One option could be to do so with a keyboard shortcut.

Another option would be to create a Google Chrome extension so that once you click on the icon it can start and stop the screen recording.

My last idea would be to have a floating button in the screen you are recording like loom (See Screenshot).

<img width="1440" alt="Screen Shot 2021-04-17 at 11 58 44 AM" src="https://user-images.githubusercontent.com/82722699/115121004-1dcf1500-9f76-11eb-8169-c469ed0107ff.png">

I hope any of these ideas are useful for you!

**Comment by joaomoreno** [comment]
Thanks for the love!

Since gifcap doesn't have focus and lives in another tab, there is no way to handle keybindings or render any UI. If you use Chrome, you do get this UI piece which lets you stop the recording:

![image](https://user-images.githubusercontent.com/22350/115200084-22213c80-a0f4-11eb-8998-814be97fdc84.png)

> Another option would be to create a Google Chrome extension so that once you click on the icon it can start and stop the screen recording.

This would be cool, definitely an idea to tackle in a separate project. 🆗
