### ISSUE TITLE
Feature Request: Export to a better format (mp4/webm) for reduced file size

### ISSUE THREAD

**Issue by Cristy94** [joaomoreno/gifcap#8]
Congrats on the project, it's really nice!

If you want to record a longer video the GIF size will become huge.
As recording is already possible and you have the frames, I think there is a way to convert those frames to mp4 or webm instead of gif, thus reducing the file size and improving the quality.

I don't know of any libraries that make this conversion, maybe something like this could be used: https://github.com/spite/ccapture.js/

Maybe ffmpeg.js could be used: https://github.com/Kagami/ffmpeg.js/blob/master/README.md

**Comment by joaomoreno** [comment]
There's been a LOT of work to be able to create the smallest GIFs possible keeping the high quality. File sizes have dramatically been reduced thanks to this, and rendering times have actually improved. More here: https://github.com/joaomoreno/gifcap/issues/6#issuecomment-623012917

Since this project is all about GIFs, we're not really interested in any other output formats. I'll close this as out of scope.

**Comment by sdenovan** [comment]
You can do the conversion yourself with ffmpeg:
`ffmpeg -i fromgifcap.gif converted.webm`

In a simple test this took an 8MB gif down to a 350KB webm with no discernible loss of quality.
